const config = {
  // # Game
  game: {
    font: 'assets/fonts/PressStart2P-Regular.ttf',
    debug: true,
    fps: 30,
    speed: 5,
    sound: true,
    gravity: 8,
    gameOverScreen: 'assets/images/game-over.png',
    gameOverWidth: 412,
    gameOverHeight: 78,
    width: 1024,
    height: 768,
    itemScore: 20,
  },
  scenes: {
    intro: {
      background: 'assets/images/initial-screen.png',
      logo: 'assets/images/logo.png',
      logoWidth: 500,
      logoHeight: 180,
    },
    level1: {
      imageFile: 'assets/images/scenario/forest.png',
      backgroundLayers: [
        'assets/images/scenario/demon-woods-bg.png',
        'assets/images/scenario/demon-woods-far-trees.png',
        'assets/images/scenario/demon-woods-mid-trees.png',
        'assets/images/scenario/demon-woods-close-trees.png',
      ],
      soundFile: 'assets/sounds/soundtrack.mp3',
    },
  },
  // # Player
  player: {
    imageFile: 'assets/images/player/player.png',
    imageFileWidth: 1280,
    imageFileHeight: 2560,
    jumpSoundFile: 'assets/sounds/jump.mp3',
    x: 40,
    y: 30,
    width: 100,
    height: 200,
    hitboxWidthMultiplier: 0.7,
    hitboxHeightMultiplier: 0.8,
    spriteX0: 0,
    spriteY0: 0,
    spriteWidth: 160, // imageFileWidth / number of horizontal frames
    spriteHeight: 320,
    animationFPS: 13,
    animations: {
      walk: { min: 17, max: 24 },
      jump: { min: 49, max: 56 },
    },
    jumpSpeed: 60,
    jumpLimit: 2,
    jumpFrames: [],
    moveRange: { min: 20, max: 200 },
    moveSpeed: 10,
  },
  coin: {
    name: 'Coin',
    imageFile: 'assets/images/coin.png',
    sound: 'assets/sounds/coin.mp3',
    imageFileWidth: 230,
    imageFileHeight: 120,
    x: 20,
    y: 30,
    width: 50,
    height: 50,
    hitboxWidthMultiplier: 1,
    hitboxHeightMultiplier: 1,
    spriteX0: 0,
    spriteY0: 0,
    spriteWidth: 120,
    spriteHeight: 120,
    animationFPS: 5,
    speed: 3,
    respawnDelay: [800, 900],
    animation: false,
    jumpFrames: [],
  },
  // # Enemies
  enemyGround: {
    name: 'Ground',
    imageFile: 'assets/images/enemies/slime.png',
    imageFileWidth: 500,
    imageFileHeight: 100,
    x: 20,
    y: 30,
    width: 52,
    height: 52,
    hitboxWidthMultiplier: 0.9,
    hitboxHeightMultiplier: 0.9,
    spriteX0: 0,
    spriteY0: 0,
    spriteWidth: 100,
    spriteHeight: 100,
    animationFPS: 15,
    speed: 15,
    respawnDelay: [500, 800],
    animation: false,
    jumpFrames: [],
  },
  enemyFlying: {
    name: 'Flying',
    imageFile: 'assets/images/enemies/bat.png',
    imageFileWidth: 256,
    imageFileHeight: 256,
    x: 20,
    y: 230,
    width: 52,
    height: 52,
    hitboxWidthMultiplier: 0.7,
    hitboxHeightMultiplier: 0.8,
    spriteX0: 0,
    spriteY0: 0,
    spriteWidth: 64,
    spriteHeight: 64,
    animationFPS: 10,
    speed: 15,
    respawnDelay: [400, 600],
    animation: { min: 13, max: 16 },
    jumpFrames: [],
  },
  enemyBig: {
    name: 'Big',
    imageFile: 'assets/images/enemies/ghost.png',
    imageFileWidth: 1280,
    imageFileHeight: 1280,
    x: 20,
    y: 30,
    width: 100,
    height: 200,
    hitboxWidthMultiplier: 0.5,
    hitboxHeightMultiplier: 0.5,
    spriteX0: 0,
    spriteY0: 0,
    spriteWidth: 160,
    spriteHeight: 320,
    animationFPS: 13,
    speed: 22,
    animation: { min: 25, max: 32 },
    respawnDelay: [900, 1100],
    jumpFrames: [],
  },
};
